// src/main/resources/static/assets/libs/swiper/react/context.js
import { createContext, useContext } from 'react';
export const SwiperSlideContext = /*#__PURE__*/createContext(null);
export const useSwiperSlide = () => {
  return useContext(SwiperSlideContext);
};
export const SwiperContext = /*#__PURE__*/createContext(null);
export const useSwiper = () => {
  return useContext(SwiperContext);
};

// target/Ecourse-1.0-SNAPSHOT/WEB-INF/classes/static/assets/libs/swiper/solid/context.js
import { createContext, useContext } from 'solid-js';
export const SwiperSlideContext = createContext(null);
export const useSwiperSlide = () => {
  return useContext(SwiperSlideContext);
};
export const SwiperContext = createContext(null);
export const useSwiper = () => {
  return useContext(SwiperContext);
};
